//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace smartRestaurant.BusinessService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BusinessServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public class BusinessService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public BusinessService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["smartRestaurant.BusinessService.BusinessService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/smartService/BusinessService.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetSalesReport", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataStream[] GetSalesReport(System.DateTime date, int empType) {
            object[] results = this.Invoke("GetSalesReport", new object[] {
                        date,
                        empType});
            return ((DataStream[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSalesReport(System.DateTime date, int empType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSalesReport", new object[] {
                        date,
                        empType}, callback, asyncState);
        }
        
        /// <remarks/>
        public DataStream[] EndGetSalesReport(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DataStream[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetInvoiceReport", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataStream[] GetInvoiceReport(System.DateTime date, int empType) {
            object[] results = this.Invoke("GetInvoiceReport", new object[] {
                        date,
                        empType});
            return ((DataStream[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInvoiceReport(System.DateTime date, int empType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInvoiceReport", new object[] {
                        date,
                        empType}, callback, asyncState);
        }
        
        /// <remarks/>
        public DataStream[] EndGetInvoiceReport(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DataStream[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/PrintInvoiceReport", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PrintInvoiceReport(System.DateTime date, int empType) {
            this.Invoke("PrintInvoiceReport", new object[] {
                        date,
                        empType});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintInvoiceReport(System.DateTime date, int empType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintInvoiceReport", new object[] {
                        date,
                        empType}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPrintInvoiceReport(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetInvoiceSummaryReport", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataStream[] GetInvoiceSummaryReport(System.DateTime date, int empType) {
            object[] results = this.Invoke("GetInvoiceSummaryReport", new object[] {
                        date,
                        empType});
            return ((DataStream[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInvoiceSummaryReport(System.DateTime date, int empType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInvoiceSummaryReport", new object[] {
                        date,
                        empType}, callback, asyncState);
        }
        
        /// <remarks/>
        public DataStream[] EndGetInvoiceSummaryReport(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DataStream[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/UpdateInvoiceHidden", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateInvoiceHidden(int invoiceID, bool hidden) {
            this.Invoke("UpdateInvoiceHidden", new object[] {
                        invoiceID,
                        hidden});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateInvoiceHidden(int invoiceID, bool hidden, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateInvoiceHidden", new object[] {
                        invoiceID,
                        hidden}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateInvoiceHidden(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/PrintSummaryMenuType", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PrintSummaryMenuType(System.DateTime date) {
            this.Invoke("PrintSummaryMenuType", new object[] {
                        date});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintSummaryMenuType(System.DateTime date, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintSummaryMenuType", new object[] {
                        date}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPrintSummaryMenuType(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/PrintSummaryReceive", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PrintSummaryReceive(System.DateTime date) {
            this.Invoke("PrintSummaryReceive", new object[] {
                        date});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintSummaryReceive(System.DateTime date, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintSummaryReceive", new object[] {
                        date}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPrintSummaryReceive(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/ExportInvoice", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataStream[] ExportInvoice(System.DateTime fromDate, System.DateTime toDate) {
            object[] results = this.Invoke("ExportInvoice", new object[] {
                        fromDate,
                        toDate});
            return ((DataStream[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExportInvoice(System.DateTime fromDate, System.DateTime toDate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExportInvoice", new object[] {
                        fromDate,
                        toDate}, callback, asyncState);
        }
        
        /// <remarks/>
        public DataStream[] EndExportInvoice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DataStream[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/DeleteSelected", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteSelected() {
            this.Invoke("DeleteSelected", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteSelected(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteSelected", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDeleteSelected(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/BackupDatabase", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BackupDatabase() {
            this.Invoke("BackupDatabase", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBackupDatabase(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BackupDatabase", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndBackupDatabase(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class DataStream {
        
        /// <remarks/>
        public string[] Column;
    }
}
