//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
// 
namespace smartRestaurant.ReserveService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReserveServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public class ReserveService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ReserveService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["smartRestaurant.ReserveService.ReserveService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/smartService/ReserveService.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableReserve", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TableReserve[] GetTableReserve(System.DateTime date) {
            object[] results = this.Invoke("GetTableReserve", new object[] {
                        date});
            return ((TableReserve[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableReserve(System.DateTime date, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableReserve", new object[] {
                        date}, callback, asyncState);
        }
        
        /// <remarks/>
        public TableReserve[] EndGetTableReserve(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TableReserve[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetTableReserve", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetTableReserve(TableReserve reserve, string custFullName) {
            object[] results = this.Invoke("SetTableReserve", new object[] {
                        reserve,
                        custFullName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetTableReserve(TableReserve reserve, string custFullName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetTableReserve", new object[] {
                        reserve,
                        custFullName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSetTableReserve(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetReserveCancel", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetReserveCancel(string reserveID) {
            object[] results = this.Invoke("SetReserveCancel", new object[] {
                        reserveID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetReserveCancel(string reserveID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetReserveCancel", new object[] {
                        reserveID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetReserveCancel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetReserveDinIn", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetReserveDinIn(string reserveID, string TableID) {
            object[] results = this.Invoke("SetReserveDinIn", new object[] {
                        reserveID,
                        TableID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetReserveDinIn(string reserveID, string TableID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetReserveDinIn", new object[] {
                        reserveID,
                        TableID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetReserveDinIn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class TableReserve {
        
        /// <remarks/>
        public int reserveTableID;
        
        /// <remarks/>
        public int tableID;
        
        /// <remarks/>
        public System.DateTime reserveDate;
        
        /// <remarks/>
        public int seat;
        
        /// <remarks/>
        public int customerID;
        
        /// <remarks/>
        public string custFirstName;
        
        /// <remarks/>
        public string custMiddleName;
        
        /// <remarks/>
        public string custLastName;
    }
}
