//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace smartRestaurant.MenuService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MenuServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public class MenuService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MenuService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["smartRestaurant.MenuService.MenuService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/smartService/MenuService.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetMenus", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenuType[] GetMenus(string AppName) {
            object[] results = this.Invoke("GetMenus", new object[] {
                        AppName});
            return ((MenuType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMenus(string AppName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMenus", new object[] {
                        AppName}, callback, asyncState);
        }
        
        /// <remarks/>
        public MenuType[] EndGetMenus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MenuType[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetOptions", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenuOption[] GetOptions(string AppName) {
            object[] results = this.Invoke("GetOptions", new object[] {
                        AppName});
            return ((MenuOption[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOptions(string AppName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOptions", new object[] {
                        AppName}, callback, asyncState);
        }
        
        /// <remarks/>
        public MenuOption[] EndGetOptions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MenuOption[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class MenuType {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public System.Double Tax1;
        
        /// <remarks/>
        public System.Double Tax2;
        
        /// <remarks/>
        public MenuItem[] MenuItems;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class MenuItem {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public int KeyID;
        
        /// <remarks/>
        public int TypeID;
        
        /// <remarks/>
        public string KeyIDText;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public System.Double Price;
        
        /// <remarks/>
        public MenuDefault[] MenuDefaults;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class MenuDefault {
        
        /// <remarks/>
        public int MenuID;
        
        /// <remarks/>
        public int OptionID;
        
        /// <remarks/>
        public int DefaultChoiceID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class OptionChoice {
        
        /// <remarks/>
        public int OptionID;
        
        /// <remarks/>
        public int ChoiceID;
        
        /// <remarks/>
        public string ChoiceName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class MenuOption {
        
        /// <remarks/>
        public int OptionID;
        
        /// <remarks/>
        public string OptionName;
        
        /// <remarks/>
        public OptionChoice[] OptionChoices;
    }
}
