//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace smartRestaurant.CustomerService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public class CustomerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CustomerService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["smartRestaurant.CustomerService.CustomerService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/smartService/CustomerService.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetCustomers", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerInformation[] GetCustomers() {
            object[] results = this.Invoke("GetCustomers", new object[0]);
            return ((CustomerInformation[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerInformation[] EndGetCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerInformation[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SearchCustomers", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerInformation[] SearchCustomers(string telephone, string fname, string mname, string lname) {
            object[] results = this.Invoke("SearchCustomers", new object[] {
                        telephone,
                        fname,
                        mname,
                        lname});
            return ((CustomerInformation[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchCustomers(string telephone, string fname, string mname, string lname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchCustomers", new object[] {
                        telephone,
                        fname,
                        mname,
                        lname}, callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerInformation[] EndSearchCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerInformation[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetCustomer", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetCustomer(CustomerInformation custInfo) {
            object[] results = this.Invoke("SetCustomer", new object[] {
                        custInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetCustomer(CustomerInformation custInfo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetCustomer", new object[] {
                        custInfo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSetCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/DeleteCustomer", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteCustomer(int custID) {
            object[] results = this.Invoke("DeleteCustomer", new object[] {
                        custID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteCustomer(int custID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteCustomer", new object[] {
                        custID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDeleteCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class CustomerInformation {
        
        /// <remarks/>
        public int CustID;
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public string MiddleName;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public string Telephone;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string Description;
    }
}
