//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace smartRestaurant.TableService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TableServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public class TableService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public TableService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["smartRestaurant.TableService.TableService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/smartService/TableService.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableList", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TableInformation[] GetTableList() {
            object[] results = this.Invoke("GetTableList", new object[0]);
            return ((TableInformation[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TableInformation[] EndGetTableList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TableInformation[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableInformation", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TableInformation GetTableInformation(int tableID) {
            object[] results = this.Invoke("GetTableInformation", new object[] {
                        tableID});
            return ((TableInformation)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableInformation(int tableID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableInformation", new object[] {
                        tableID}, callback, asyncState);
        }
        
        /// <remarks/>
        public TableInformation EndGetTableInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TableInformation)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableStatus", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TableStatus[] GetTableStatus() {
            object[] results = this.Invoke("GetTableStatus", new object[0]);
            return ((TableStatus[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableStatus(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableStatus", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TableStatus[] EndGetTableStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TableStatus[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class TableInformation {
        
        /// <remarks/>
        public int TableID;
        
        /// <remarks/>
        public int NumberOfSeat;
        
        /// <remarks/>
        public string TableName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class TableStatus {
        
        /// <remarks/>
        public int TableID;
        
        /// <remarks/>
        public string TableName;
        
        /// <remarks/>
        public bool InUse;
    }
}
