//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace smartRestaurant.CheckBillService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CheckBillServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public class CheckBillService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CheckBillService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["smartRestaurant.CheckBillService.CheckBillService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/smartService/CheckBillService.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetInvoice", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Invoice GetInvoice(int orderBillID) {
            object[] results = this.Invoke("GetInvoice", new object[] {
                        orderBillID});
            return ((Invoice)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInvoice(int orderBillID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInvoice", new object[] {
                        orderBillID}, callback, asyncState);
        }
        
        /// <remarks/>
        public Invoice EndGetInvoice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Invoice)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetInvoiceByID", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Invoice GetInvoiceByID(int invoiceID) {
            object[] results = this.Invoke("GetInvoiceByID", new object[] {
                        invoiceID});
            return ((Invoice)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInvoiceByID(int invoiceID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInvoiceByID", new object[] {
                        invoiceID}, callback, asyncState);
        }
        
        /// <remarks/>
        public Invoice EndGetInvoiceByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Invoice)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SendInvoice", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendInvoice(Invoice invoice) {
            object[] results = this.Invoke("SendInvoice", new object[] {
                        invoice});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendInvoice(Invoice invoice, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendInvoice", new object[] {
                        invoice}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSendInvoice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetComputeBillPrice", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillPrice GetComputeBillPrice(int orderBillID) {
            object[] results = this.Invoke("GetComputeBillPrice", new object[] {
                        orderBillID});
            return ((BillPrice)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetComputeBillPrice(int orderBillID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetComputeBillPrice", new object[] {
                        orderBillID}, callback, asyncState);
        }
        
        /// <remarks/>
        public BillPrice EndGetComputeBillPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BillPrice)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTodayTip", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Double GetTodayTip() {
            object[] results = this.Invoke("GetTodayTip", new object[0]);
            return ((System.Double)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTodayTip(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTodayTip", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Double EndGetTodayTip(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Double)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetDescription", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDescription(string id) {
            object[] results = this.Invoke("GetDescription", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDescription(string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDescription", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetDescription(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class Invoice {
        
        /// <remarks/>
        public int invoiceID;
        
        /// <remarks/>
        public int paymentMethodID;
        
        /// <remarks/>
        public int orderBillID;
        
        /// <remarks/>
        public int point;
        
        /// <remarks/>
        public System.Double totalPrice;
        
        /// <remarks/>
        public System.Double tax1;
        
        /// <remarks/>
        public System.Double tax2;
        
        /// <remarks/>
        public System.Double totalDiscount;
        
        /// <remarks/>
        public System.Double totalReceive;
        
        /// <remarks/>
        public int employeeID;
        
        /// <remarks/>
        public int refInvoice;
        
        /// <remarks/>
        public InvoiceDiscount[] discounts;
        
        /// <remarks/>
        public InvoicePayment[] payments;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class InvoiceDiscount {
        
        /// <remarks/>
        public int invoiceDiscountID;
        
        /// <remarks/>
        public int invoiceID;
        
        /// <remarks/>
        public int promotionID;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class BillPrice {
        
        /// <remarks/>
        public System.Double totalPrice;
        
        /// <remarks/>
        public System.Double totalDiscount;
        
        /// <remarks/>
        public System.Double totalTax1;
        
        /// <remarks/>
        public System.Double totalTax2;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class InvoicePayment {
        
        /// <remarks/>
        public int paymentMethodID;
        
        /// <remarks/>
        public System.Double receive;
    }
}
