//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace smartRestaurant.PaymentService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaymentServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public class PaymentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public PaymentService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["smartRestaurant.PaymentService.PaymentService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/smartService/PaymentService.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetPaymentMethods", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PaymentMethod[] GetPaymentMethods() {
            object[] results = this.Invoke("GetPaymentMethods", new object[0]);
            return ((PaymentMethod[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPaymentMethods(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPaymentMethods", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public PaymentMethod[] EndGetPaymentMethods(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PaymentMethod[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetCoupons", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PromotionCard[] GetCoupons() {
            object[] results = this.Invoke("GetCoupons", new object[0]);
            return ((PromotionCard[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCoupons(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCoupons", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public PromotionCard[] EndGetCoupons(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PromotionCard[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetGiftVouchers", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PromotionCard[] GetGiftVouchers() {
            object[] results = this.Invoke("GetGiftVouchers", new object[0]);
            return ((PromotionCard[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGiftVouchers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGiftVouchers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public PromotionCard[] EndGetGiftVouchers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PromotionCard[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetDiscounts", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Discount[] GetDiscounts() {
            object[] results = this.Invoke("GetDiscounts", new object[0]);
            return ((Discount[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDiscounts(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDiscounts", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Discount[] EndGetDiscounts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Discount[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class PaymentMethod {
        
        /// <remarks/>
        public int paymentMethodID;
        
        /// <remarks/>
        public string paymentMethodName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class Discount {
        
        /// <remarks/>
        public int promotionID;
        
        /// <remarks/>
        public int promotionType;
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        public System.Double amount;
        
        /// <remarks/>
        public System.Double discountPercent;
        
        /// <remarks/>
        public System.Double discountAmount;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public class PromotionCard {
        
        /// <remarks/>
        public int promotionID;
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        public System.Double amount;
    }
}
